name: Release to Maven Central

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Import GPG key
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --yes --import
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Set up gpg-agent
      run: |
        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        echo RELOADAGENT | gpg-connect-agent
        echo -e "pinentry-mode loopback\n" >> ~/.gnupg/gpg.conf

    - name: Build with Maven
      run: |
        mvn clean deploy -Dgpg.passphrase=$GPG_PASSPHRASE \
                         -Dgpg.keyname=$GPG_KEY_ID \
                         -Dgpg.executable=gpg \
                         -Dgpg.pinentry.mode=loopback
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
